# Site settings
title: RubySG
description: >-
  Hello! We are the Ruby community in Singapore! Join us at our next Monthly meetup or RailsGirls event.
url: "https://ruby.sg"
baseurl: "/"
github_username: rubysg

# Build settings
markdown: kramdown
# theme: minima

# GitHub Pages plugins (automatically enabled)
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sass_dir: assets/_sass
  style: compressed
